//server routes
module.exports = {
    HttpRoot: "http://localhost:4000",
    Avatars: "avats",
    //HttpRoot: "https://t3dweb.herokuapp.com",
    WebSocketRoot: "wss://t3dweb.herokuapp.com",
    webSocketRoute: "ws",
    wsGamePlayRoute: "gameplay",
    wsGlobalRoute: "global",
    SignUp: "signup",
    SignIn: "signin",
    Users: "users",
    Private: "private",
    Credentials: "credentials",
    MyAvatar: "avatar",
    PasswordChange: "password",
    Friends: "friends",
    Public: "public",
    Administrators: "administrators",
    Games: "games",
    Mine: "mine",
    Chats: "chats",
    SingleChat: "single",
    Interactions: "interact",
    Notices: "notices",
    NoticeManagement: "manage"
};